=== SamuelGH7/classwork/classwork.dtd
<!ELEMENT family (member)*>
<!ATTLIST element-name attribute-name ID #REQUIRED>

<!ELEMENT member (name,age,gender)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>

=== SamuelGH7/classwork/classwork.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <family>
    <member role="father" gender="male" age="40">Jake</member>
    <member role="motther" gender="female" age="38">Kat</member>
    <member role="son" gender="male" age="18">Jack</member>
    <member role="daughter" gender="female" age="15">Kim</member>
    <member role="pet" gender="male" age="1">Sid</member>
</family> -->

<!DOCTYPE family SYSTEM "classwork.dtd">

<family>

    <member>
        <name>Jake</name>
        <age>40</age>
        <gender>Male</gender>
    </member>

    <member>
        <name>Kat</name>
        <age>38</age>
        <gender>Female</gender>
    </member>

    <member>
        <name>Jack</name>
        <age>18</age>
        <gender>Male</gender>
    </member>

    <member>
        <name>Kim</name>
        <age>15</age>
        <gender>Female</gender>
    </member>

    <member>
        <name>Sid</name>
        <age>1.5</age>
        <gender>Male</gender>
    </member>
    
</family>
